### PR TITLE
Use avx micro

### PR DESCRIPTION
**Pull request by YingboMa**
lubench

`RF{n}` denotes RecursiveFactorization.jl with the block size `n`.

### CODE REVIEW

**Comment by haampie** [comment]
```
julia> versioninfo()
Julia Version 1.5.0-DEV.872
Commit 52c9e3df13 (2020-05-06 21:07 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: AMD Ryzen 7 3700X 8-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
```

Cross-over point is a bit higher:

```
julia> ns
4:32:772

julia> bas_mflops'
1×25 LinearAlgebra.Adjoint{Float64,Array{Float64,1}}:
 0.456176  2.0732  1.98411  3.70137  5.28349  8.37031  9.3997  12.645  15.852  19.3869  24.2657  29.3414  33.8526  40.1972  44.5648  49.9508  56.5037  65.2515  74.1768  82.3366  90.219  100.738  112.161  122.844  133.155

julia> rec8_mflops'
1×25 LinearAlgebra.Adjoint{Float64,Array{Float64,1}}:
 0.864786  18.0868  24.6021  24.4194  25.5572  26.5373  46.3583  54.7939  62.6628  71.128  70.7694  78.0759  80.0345  85.4232  85.9247  90.9074  86.849  88.044  89.0744  90.1692  67.5839  92.2557  93.27  94.218  93.6221

julia> rec16_mflops'
1×25 LinearAlgebra.Adjoint{Float64,Array{Float64,1}}:
 0.858966  18.1  24.7473  24.5638  25.5785  26.4895  51.7918  62.357  70.0925  77.7574  77.0638  81.8425  84.9068  89.0839  91.1266  93.1842  88.9145  89.7999  90.0739  91.742  89.8632  93.577  94.3629  95.8648  94.4576

julia> rec32_mflops'
1×25 LinearAlgebra.Adjoint{Float64,Array{Float64,1}}:
 0.861189  18.1066  24.762  24.4781  25.5804  26.559  56.2461  63.8304  68.9619  76.4658  77.4705  81.0202  83.3155  86.7616  88.0898  91.7577  88.5261  88.1098  88.7526  90.4033  89.6316  91.5969  91.6373  94.2861  92.3442

julia> ref_mflops'
1×25 LinearAlgebra.Adjoint{Float64,Array{Float64,1}}:
 1.32156  7.27439  7.60573  7.5959  7.66819  7.93752  8.04565  8.13914  8.15377  8.22842  8.23492  8.238  8.28366  8.27728  8.28567  8.29675  8.16349  8.19  8.27289  8.29883  8.20049  8.25344  8.25535  8.26801  8.24367
```

**Comment by chriselrod** [comment]
For BLAS, I set `BLAS.set_num_threads(1)`. MKL, which I used below, benefits very early from threading.
```julia
julia> ns
4:32:484

julia> bas_mflops'
1×16 Adjoint{Float64,Array{Float64,1}}:
 1.41084  10.7231  23.9774  37.5832  51.2121  62.2593  70.8946  79.1566  81.891  88.7153  88.9651  91.5851  91.3338  92.6732  95.5583  97.5375

julia> rec8_mflops'
1×16 Adjoint{Float64,Array{Float64,1}}:
 0.782971  17.3671  25.5093  53.8489  70.5918  83.9141  94.1819  99.879  103.405  105.642  106.1  106.097  107.213  108.87  109.647  99.7817

julia> rec16_mflops'
1×16 Adjoint{Float64,Array{Float64,1}}:
 0.777886  17.5981  26.1441  58.7227  73.638  86.1298  96.0709  98.3181  101.242  105.637  106.305  106.662  105.796  107.89  110.27  110.874

julia> rec32_mflops'
1×16 Adjoint{Float64,Array{Float64,1}}:
 0.783776  18.8401  26.491  56.7313  69.4503  79.5908  87.4162  92.0404  93.6189  96.0736  96.8095  98.252  99.4664  101.091  95.6343  99.7928

julia> ref_mflops'
1×16 Adjoint{Float64,Array{Float64,1}}:
 1.298  6.39745  6.57548  6.70583  6.99637  7.18432  7.31917  7.40996  7.49471  7.55824  7.58217  7.5936  7.56384  7.46406  7.4024  7.4618

julia> versioninfo(verbose=true)
Julia Version 1.5.0-DEV.872
Commit 1345a043d2* (2020-05-06 02:30 UTC)
Platform Info:
  OS: Linux (x86_64-generic-linux)
  uname: Linux 5.6.8-945.native #1 SMP Thu Apr 30 17:40:25 PDT 2020 x86_64 unknown
  CPU: Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz:
                 speed         user         nice          sys         idle          irq
       #1-36  4589 MHz   29753860 s       3290 s     197302 s  809521622 s      74333 s

  Memory: 125.55207824707031 GB (79424.8359375 MB free)
  Uptime: 233224.0 sec
  Load Avg:  0.02734375  0.17626953125  0.33984375
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
```

I'm pretty sure the GFLOPS aren't totally accurate. With 2 AVX2 FMAs per clock, haampie's Ryzen would have to have been running at at least 6 GHz to reach 95.8648 double precision flops.

**Comment by haampie** [comment]
The algorithm for A of size m x n would be:

```
for i = 1 : m, j = i + 1 : m, k = i + 1 : n
  a[j, k] -= a[j, i] / a[i, i] * a[i, k]
end
```
with `a[j, i] / a[i, i]` computed outside of the inner loop, so I would say the flops are

https://www.wolframalpha.com/input/?i=Expand%5BSum%5B2%28m+-+i%29+*+%28n+-+i%29+%2B+%28m+-+i%29%2C+%7Bi%2C+1%2C+m%7D%5D%5D

`m^2 n -m^3/3 + m^2/2 - m n - m/6`

* and - counted as two flops. If you count them as one flop:

https://www.wolframalpha.com/input/?i=Expand%5BSum%5B%28m+-+i%29+*+%28n+-+i%29+%2B+%28m+-+i%29%2C+%7Bi%2C+1%2C+m%7D%5D%5D

(m^2 n)/2 -m^3/6 + m^2/2 - (m n)/2 - m/3

**Comment by chriselrod** [comment]
For all I know, you could've decided this benchmark was [worth the liquid nitrogen](https://valid.x86.fr/cf0bsx), although that "theory" assumed OpenBLAS's 133.155 GFLOPS comes from multithreading.

That said, I'm currently running vs multithreaded MKL (because YingoboMa wanted that comparison) over the range `4:4:800`, using GFlops.jl for the GFLOPS.

**Comment by YingboMa** [comment]
It seems like the performance is not blocksize-sensitive, and the more important parameter here is `threshold`. Also, btw, there are more to tune :P, see https://github.com/YingboMa/RecursiveFactorization.jl/blob/18f57209c84f043380c3d8ba048fc9755c032421/src/lu.jl#L34. That is the splitting strategy.

**Comment by chriselrod** [comment]
MKL of course wins with multithreading, by an increasing margin as we increase the problem size and it can use more cores:

newplot(3)

This CPU's peak is 131.2 GFLOPS (AVX512 speed is pinned to 4.1 GHz in the bios, no boost, independent of the number of cores, so 4.1 (GHz) * 16 (ops/fma) * 2 (fma/cycle) = 131.2).

However, unlike BLAS, 100% of our floating point operations aren't FMA, so the theoretical peak will be much lower. Those divisions are much slower, but we'd only have O(N^2) divisions (or O(N^1) if we invert, and then multiply by the inverse). Based on the below, LinearAlgebra.generic_lufact performs O(N^1) divisions:
```julia
julia> N = 100;

julia> A = rand(N, N);

julia> Acopy = copy(A);

julia> ops_count = @count_ops LinearAlgebra.generic_lufact!(Acopy)
Flop Counter:
 add32: 0
 sub32: 0
 mul32: 0
 div32: 0
 add64: 0
 sub64: 328350
 mul64: 333300
 div64: 100
 sqrt32: 0
 sqrt64: 0


julia> num_ops = GFlops.flop(ops_count)
661750
```

This is about half as much as:
```julia
julia> luflops(m,n) = m^2 * n - m^3/3 + m^2/2 - m * n - m/6
luflops (generic function with 1 method)

julia> luflops(n) = luflop(n,n)
luflops (generic function with 2 methods)

julia> luflops(100)
1333300

julia> ans >> 1
666650
```
I'm inclined to trust `Gflops.jl` here.
```julia
julia> maximum(rec8_mflops)
83.5141029567983

julia> maximum(rec16_mflops)
80.65113411536265

julia> maximum(rec32_mflops)
75.01126458164664
```
It reported 83.5 gflops as the maximum, which occured at N = 536.
```julia
julia> N = 536
536

julia> A = rand(N, N); Acopy = copy(A);

julia> ops_count = @count_ops LinearAlgebra.generic_lufact!(Acopy)
Flop Counter:
 add32: 0
 sub32: 0
 mul32: 0
 div32: 0
 add64: 0
 sub64: 51186660
 mul64: 51330040
 div64: 536
 sqrt32: 0
 sqrt64: 0


julia> num_ops = GFlops.flop(ops_count)
102517236

julia> luflops(536)
205320696
```
My CPU's theoretical peak is 131.2 GFLOPS (4.1 GHz * 16 flop/fma * 2fma/cycle), so 167 GFLOPS seems unlikely.
I haven't double checked the triangular sum calculations.

**Comment by haampie** [comment]
you might have used the old `luflop` function accidentally when defining `luflops(n) = luflop(n,n)`

```
julia> luflops(m,n) = m^2 * n - m^3/3 + m^2/2 - m * n - m/6
julia> luflops(n) = luflops(n,n)
julia> luflops(100)
661650.0000000001
```

**Comment by chriselrod** [comment]
I should have realized it was returning integers instead of floating point numbers, despite the 1/2!

**Comment by haampie** [comment]
Just for reference, the optimal implementation would be:

```
muls(m, n) = (m - 1) * m * (3n - m + 2) ÷ 6
subs(m, n) = (m - 1) * m * (3n - m - 1) ÷ 6
divs(m, n) = m
total(m, n) = muls(m, n) + subs(m, n) + divs(m, n)
```

I believe the inner loop could be one fma instruction with a negation right? In that case the counts would be:

```
fmas(m, n) = (m - 1) * m * (3n - m - 1) ÷ 6
muls(m, n) = (m - 1) * m ÷ 2
divs(m, n) = m
total(m, n) = fmas(m, n) + muls(m, n) + divs(m, n)
```

**Comment by YingboMa** [comment]
FLOP count confuses the heck out of me
```julia
julia> function luflop(m, n=m; innerflop=2)
           sum(1:min(m, n)) do k
               invflop = 1
               scaleflop = isempty(k+1:m) ? 0 : sum(k+1:m)
               updateflop = isempty(k+1:n) ? 0 : sum(k+1:n) do j
                   isempty(k+1:m) ? 0 : sum(k+1:m) do i
                       innerflop
                   end
               end
               invflop + scaleflop + updateflop
           end
       end
luflop (generic function with 2 methods)

julia> luflop(100; innerflop=1)
661750

julia> luflop(100; innerflop=2)
990100
```

I get the same number with GFlops if I count `A[i,j] -= A[i,k]*A[k,j]` as 1 flop.

**Comment by YingboMa** [comment]
Let's move the benchmarking and tuning to #7.

**Comment by ChrisRackauckas** [comment]
Time to rerun some DiffEqBenchmarks :)

**Pull request merged**
