### PR TITLE
Turn off warnings

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
https://github.com/SciML/DifferentialEquations.jl/issues/810#issuecomment-957129984

### CODE REVIEW

**Comment by YingboMa** [comment]
Some how macOS fails with `StackOverflowError`

**Review by chriselrod — APPROVED** [review]
I had an issue, someone complaining on HackerNews, and at a few other places about it not warning you when it doesn't work, so I figured I'd go with that as the default behavior.

It's mentioned in the docstring if you `??@turbo` (help mode + 1 extra question mark for the extended docstring).

**Comment by ChrisRackauckas** [comment]
Yeah I think that can make sense for a lot of high level uses, but when it's deep inside of a library and throwing a warning in a legit use case 😅

**Comment by chriselrod** [comment]
I opened up the source to have the warning explain how to disable it, only to realize I already did that: 
```julia
julia> using LoopVectorization, ForwardDiff

julia> function sum_turbo(x)
           s = zero(eltype(x))
           @turbo for i ∈ eachindex(x)
               s += x[i]
           end
           s
       end
sum_turbo (generic function with 1 method)

julia> ForwardDiff.gradient(sum_turbo, rand(4))
┌ Warning: #= REPL[7]:3 =#:
│ `LoopVectorization.check_args` on your inputs failed; running fallback `@inbounds @fastmath` loop instead.
│ Use `warn_check_args=false`, e.g. `@turbo warn_check_args=false ...`, to disable this warning.
└ @ Main ~/.julia/dev/LoopVectorization/src/condense_loopset.jl:825
4-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
```

**Comment by ChrisRackauckas** [comment]
Yeah discoverability isn't the issue. It's just when it's baked deep into a library the user cannot modify.

**Pull request merged**
