### PR TITLE
TriangularSolve.jl for ldiv!

### PR DESCRIPTION
**Pull request by chriselrod**
Versus single threaded OpenBLAS and single threaded MKL:
image
image

TriangularSolve.jl will need a release before tests pass.

### CODE REVIEW

**Comment by YingboMa** [comment]
What's the cut off for multithreaded solve? I think we might want to introduce polyester to trsm as well.

**Comment by chriselrod** [comment]
M1:
image

The M1 has 32 registers available. I should probably try and make explicit use of that in TriangularSolve.jl.

Currently, it only does so implicitly in a manner that happens to work out for AVX/AVX2/AVX512:

If your vector width is `W`, you can work with a `WxW` block for solves, requiring `W` registers. TriangularSolve uses 3 of these blocks at a time.
AVX512 has 32 registers, and 3 8x8 blocks requires 24 registers. 
AVX(2) has 16 registers, and 3 4x4 blocks requires 12 registers.

You need a few registers for holding the values you're operating on these blocks with, so we don't want the blocks to occupy all of them, so this should be close to ideal.

But ARM NEON has 32 registers, and 3 2x2 blocks requires only 6 of them.
Maybe I should use 12 2x2 blocks? Seems extreme/will require a little experimenting.

**Comment by chriselrod** [comment]
> What's the cut off for multithreaded solve? I think we might want to introduce polyester to trsm as well.

It is currently single threaded.

**Comment by YingboMa** [comment]
Have you tested Apple Accelerate? Is it faster than OpenBLAS?

**Comment by chriselrod** [comment]
> Have you tested Apple Accelerate? Is it faster than OpenBLAS?

I haven't tested it. I have already added trsm here though, so I should try:
https://github.com/chriselrod/AppleAccelerateLinAlgWrapper.jl

I don't recall how good accelerate is at trsm, but it's gemm is way faster than OpenBLAS, because it uses Apple's undocumented matrix coprocessor.

**Comment by chriselrod** [comment]
image
Need to set the recursion threshold smaller for the M1.

**Comment by chriselrod** [comment]
Haswell:
image

Maybe a recursion threshold of 48 for AVX512, and 40 for everyone else?

**Comment by chriselrod** [comment]
Haswell vs MKL:
image

**Comment by chriselrod** [comment]
TriangularSolve.jl doesn't actually do any cache-level blocking yet, which would explain the performance degradation we see, particularly for Haswell, which has much smaller caches than the other chips I benchmarked on above.

**Comment by chriselrod** [comment]
2 cores on Haswell:
image

**Comment by chriselrod** [comment]
image
image
Regression for small sizes, improvement for larger sizes.

I think the code would require serious reworking / thinking about how data should be distributed to cores to minimize memory movement to actually be able to compete with MKL here.

**Comment by chriselrod** [comment]
Performance for large matrices is a little better due to blocking when single threaded:
image

A block size of 8 seems better for large matrices (at least when multithreaded), while 16 seems better for small ones. The regression for small matrices above was due to using 8.

**Comment by chriselrod** [comment]
For comparison, here is the latest release of RecursiveFactorization using MKL's ldiv vs MKL's lu:
image

**Comment by YingboMa** [comment]
The test failures looks a bit weird.

**Comment by chriselrod** [comment]
```julia
 [ Info: size: 300 × 302, T = Float32, p = false
Test LU factorization: Test Failed at /Users/runner/work/RecursiveFactorization.jl/RecursiveFactorization.jl/test/runtests.jl:14
  Expression: norm(MF.L * MF.U - A[MF.p, :], Inf) < 100 * sqrt(eps(real(one(float(first(A))))))
   Evaluated: 1.0432473f0 < 0.0345267f0
Stacktrace:
 [1] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] testlu(A::Matrix{Float32}, MF::LinearAlgebra.LU{Float32, Matrix{Float32}}, BF::LinearAlgebra.LU{Float32, Matrix{Float32}})
   @ Main ~/work/RecursiveFactorization.jl/RecursiveFactorization.jl/test/runtests.jl:14
```
```julia
[ Info: size: 300 × 302, T = Float32, p = false
Test LU factorization: Test Failed at /Users/runner/work/RecursiveFactorization.jl/RecursiveFactorization.jl/test/runtests.jl:14
  Expression: norm(MF.L * MF.U - A[MF.p, :], Inf) < 100 * sqrt(eps(real(one(float(first(A))))))
   Evaluated: 1.0432473f0 < 0.0345267f0
Stacktrace:
 [1] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] testlu(A::Matrix{Float32}, MF::LinearAlgebra.LU{Float32, Matrix{Float32}}, BF::LinearAlgebra.LU{Float32, Matrix{Float32}})
   @ Main ~/work/RecursiveFactorization.jl/RecursiveFactorization.jl/test/runtests.jl:14
```
Seems to be numerically unstable.

**Comment by YingboMa** [comment]
That's 30 times more error. Maybe just do `100 * (n+m)/20 * eps`?

**Comment by YingboMa** [comment]
Let's merge this after JuliaCon. Doing big overhauls during JuliaCon is probably not a great idea.

**Comment by chriselrod** [comment]
Okay. We should also probably discuss/benchmark/modify threading a bit to make sure it isn't more problematic than BLAS's threads when used inside multithreaded code, otherwise we could accidentally cause regressions.

**Comment by ChrisRackauckas** [comment]
1 thread and too lazy to let it finish:

```julia
Progress:   6%|█████████                                                                                                                           |  ETA: 0:49:51
  Size:                    (17, 17)
  RecursiveFactorization:  (MedianGFLOPS = 3.053, MaxGFLOPS = 5.323)
  MKL:                     (MedianGFLOPS = 2.047, MaxGFLOPS = 2.198)
  OpenBLAS:                (MedianGFLOPS = 2.509, MaxGFLOPS = 2.762)
  
Progress:   6%|████████                                                                                                                            |  ETA: 0:50:05
  Size:                    (486, 486)
  RecursiveFactorization:  (MedianGFLOPS = 61.48, MaxGFLOPS = 63.66)
  MKL:                     (MedianGFLOPS = 44.45, MaxGFLOPS = 46.02)
  OpenBLAS:                (MedianGFLOPS = 30.56, MaxGFLOPS = 31.42)
```

threads before:

```julia
Benchmark Result of Matrix{Float64}, threaded = true
499×4 DataFrame
 Row │ Size   RecursiveFactorization  MKL        OpenBLAS
     │ Int64  Float64                 Float64    Float64
─────┼──────────────────────────────────────────────────────
   1 │     2               0.0657403   0.063588   0.0184379
   2 │     3               0.199637    0.201668   0.0583181
   3 │     4               0.455492    0.477975   0.139624
   4 │     5               0.725659    0.723201   0.237872
   5 │     6               1.10103     1.10433    0.380987
   6 │     7               1.49487     1.57906    0.502137
   7 │     8               1.85671     1.84096    0.698263
   8 │     9               2.2043      2.30905    0.840349
  ⋮  │   ⋮              ⋮                 ⋮          ⋮
 493 │   494              27.7117     88.2169    13.2343
 494 │   495              27.0705     92.0548    13.3017
 495 │   496              28.8698     96.734     13.2336
 496 │   497              27.846      94.3745    13.27…
```

threads after:

```julia
Size:                    (5, 5)
RecursiveFactorization:  (MedianGFLOPS = 0.6973, MaxGFLOPS = 0.7495)
MKL:                     (MedianGFLOPS = 0.6986, MaxGFLOPS = 0.7502)
OpenBLAS:                (MedianGFLOPS = 0.2265, MaxGFLOPS = 0.2423)

Size:                    (498, 498)
RecursiveFactorization:  (MedianGFLOPS = 66.61, MaxGFLOPS = 91.24)
MKL:                     (MedianGFLOPS = 78.8, MaxGFLOPS = 94.33)
OpenBLAS:                (MedianGFLOPS = 14.0, MaxGFLOPS = 14.61)
```

**Comment by chriselrod** [comment]
> 1 thread and too lazy to let it finish:
> 
> ```julia
>   OpenBLAS:                (MedianGFLOPS = 30.56, MaxGFLOPS = 31.42)
> ```

> 
> threads after:
> 
> ```julia
> OpenBLAS:                (MedianGFLOPS = 14.0, MaxGFLOPS = 14.61)
> ```

Oh, OpenBLAS...

**Pull request merged**
