### PR TITLE
Tuning parameters

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Comment by YingboMa** [comment]
Plot in commit 37f28ecb96f7e51416abc515aa935bfb6f030d49
lubench
RF{n} denotes `n` recursion threshold.

The really high peak is probably a fluke with weird pivoting. I should copy the matrix every time.

**Comment by YingboMa** [comment]
e58dd743ddced0a03ede9841f2a213411e9f1dc2 should give more stable timing

lubench

**Comment by YingboMa** [comment]
[lubench.pdf](https://github.com/YingboMa/RecursiveFactorization.jl/files/4594542/lubench.pdf)
lubench

My laptop seems to be terrible at giving stable timing.

**Comment by chriselrod** [comment]
newplot(6)

Reference above is `RecursiveFactorization._generic_lu!`. I don't see the need to keep benchmarking `LinearAlgebra.generic_lu!`.

**Comment by YingboMa** [comment]
CPU: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz:

lubench

**Comment by chriselrod** [comment]
> CPU: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz:

Regarding GFLOP discrepency, it's running at little more than half the clock speed, and has [only 1](https://ark.intel.com/content/www/us/en/ark/products/123550/intel-xeon-silver-4114-processor-13-75m-cache-2-20-ghz.html) AVX512 FMA unit instead of the typical 2.

**Comment by YingboMa** [comment]
72 seems like a good threshold for AVX512.

**Comment by YingboMa** [comment]
CPU: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz:
[lubench.pdf](https://github.com/YingboMa/RecursiveFactorization.jl/files/4595030/lubench.pdf)
56 should be better in theory

**Comment by chriselrod** [comment]
newplot(8)
On my computer.

**Comment by chriselrod** [comment]
The plot looks very different with OpenBLAS:
newplot(9)

Looks like performance is largely bound by trsm.

**Comment by chriselrod** [comment]
lu_float64
```julia
julia> versioninfo(verbose=true)
Julia Version 1.5.0-DEV.876
Commit 0c388fc340 (2020-05-07 20:12 UTC)
Platform Info:
  OS: Linux (x86_64-generic-linux)
  uname: Linux 5.5.13-924.native #1 SMP Wed Mar 25 11:02:50 PDT 2020 x86_64 unknown
  CPU: Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz:
                 speed         user         nice          sys         idle          irq
       #1-20  3520 MHz   52555252 s       8518 s   18493182 s  7084603429 s    2356521 s

  Memory: 31.04729461669922 GB (4738.20703125 MB free)
  Uptime: 3.582139e6 sec
  Load Avg:  2.36669921875  1.39111328125  1.59814453125
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by ChrisRackauckas** [comment]
Wow. I can't read the label, but I assume the red line is some tuned method that switches between the two?

**Comment by chriselrod** [comment]
Yingobo Ma made the plots better on the latest commit; different computer:
lu_float64

```julia
julia> versioninfo(verbose=true)
Julia Version 1.5.0-DEV.873
Commit d4d930399c* (2020-05-07 00:56 UTC)
Platform Info:
  OS: Linux (x86_64-generic-linux)
  uname: Linux 5.6.11-948.native #1 SMP Wed May 6 00:04:43 PDT 2020 x86_64 unknown
  CPU: Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz:
                 speed         user         nice          sys         idle          irq
       #1-36  1286 MHz   38050344 s          4 s     135133 s  369023540 s      75981 s

  Memory: 125.55207824707031 GB (123710.91015625 MB free)
  Uptime: 113142.0 sec
  Load Avg:  0.3828125  2.04150390625  1.5458984375
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-10.0.0 (ORCJIT, skylake)
```

Yeah, the red version switches between the two. 110 seems to be the right place to switch for Julia Computing's computer with an AVX512 Xeon that has just 1 FMA unit, as well as for these two chips with two units.

Haswell seems trickier. Yingbo's laptop likes very large thresholds for where to switch, while a Haswell Xeon I ran it on seems to prefer 80.

**Pull request closed without merging**
