### PR TITLE
1.7 compat

### LINKED ISSUE #26: Breakage in upcoming Julia 1.7
The tests for this package fails on the upcoming 1.7

```
ERROR: LoadError: MethodError: no method matching generic_lufact!(::Matrix{Float64}, ::Val{true}; check=true)
Closest candidates are:
  generic_lufact!(::StridedMatrix{T}) where T at /workspace/srcdir/usr/share/julia/stdlib/v1.7/LinearAlgebra/src/lu.jl:136 got unsupported keyword argument "check"
  generic_lufact!(::StridedMatrix{T}, !Matched::Union{LinearAlgebra.NoPivot, LinearAlgebra.RowMaximum}; check) where T at /workspace/srcdir/usr/share/julia/stdlib/v1.7/LinearAlgebra/src/lu.jl:136
Stacktrace:
  [1] #lu!#2
    @ ~/.julia/packages/RecursiveFactorization/ec89K/src/lu.jl:12 [inlined]
  [2] lu! (repeats 2 times)
    @ ~/.julia/packages/RecursiveFactorization/ec89K/src/lu.jl:9 [inlined]
  [3] (::DefaultLinSolve)(x::Vector{Float64}, A::Matrix{Float64}, b::Vector{Float64}, update_matrix::Bool; reltol::Nothing, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ DiffEqBase ~/.julia/packages/DiffEqBase/lULzQ/src/linear_nonlinear.jl:77
  [4] DefaultLinSolve
    @ ~/.julia/packages/DiffEqBase/lULzQ/src/linear_nonlinear.jl:63 [inlined]
...
```

Since `generic_lufact!` is an internal method, I believe this should be fixed in the package.

### PR DESCRIPTION
**Pull request by YingboMa**
Fix #26

### CODE REVIEW

**Comment by YingboMa** [comment]
Bad news:
```julia
┌ Warning: `vendor()` is deprecated, use `BLAS.get_config()` and inspect the output instead
│   caller = pick_threshold at lu.jl:33 [inlined]
└ @ Core ~/src/julia/RecursiveFactorization/src/lu.jl:33
```
and
```julia
julia> @btime BLAS.get_config().loaded_libs
  106.706 μs (4960 allocations: 300.77 KiB)
1-element Vector{LinearAlgebra.BLAS.LBTLibraryInfo}:
 LBTLibraryInfo(libopenblas64_.dylib, ilp64)
```

**Comment by chriselrod** [comment]
Looks like we have no choice but to make this faster than MKL.

**Comment by ChrisRackauckas** [comment]
Sounds like a good plan.

**Comment by chriselrod** [comment]
> Sounds like a good plan.

Done: https://github.com/YingboMa/RecursiveFactorization.jl/pull/28

(Although I'll need to benchmark on more platforms.)

**Pull request merged**
